{% set name = "enmapbox" %}
{% set version = "0.1.0" %}
{% set qgis_ltr_version = "3.40" %}  # adjust to current LTR

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

outputs:
  # -------------------
  # Lite / core version
  # -------------------
  - name: enmapbox-lite
    noarch: generic
    requirements:
      run:
        - python >=3.10
        - qgis >={{ qgis_ltr_version }}
        - colorama
        - gdal
        - matplotlib
        - numpy
        - scikit-learn
    test:
      imports:
        - qgis
        - osgeo.gdal

  # ------------
  # Full version
  # ------------
  - name: enmapbox-full
    noarch: generic
    requirements:
      run:
        - enmapbox-lite

        - astropy
        - catboost
        - enfrosp_enmapboxapp
        - enpt >=1.2.1
        - enpt_enmapboxapp >=1.0.2
        - h5py
        - lightgbm
        - lightning
        - netcdf4
        - numba >=0.56.4
        - opencv
        - pandas
        - pyopengl
        - pytorch
        - segmentation-models-pytorch
        - sympy
        - tensorboard
        - torchvision
        - xgboost

    test:
      commands:
        # QGIS Python must start
        - |
          export QT_QPA_PLATFORM=offscreen
          python -c "from qgis.core import QgsApplication; \
                     app = QgsApplication([], False); \
                     app.initQgis(); \
                     print('QGIS OK'); \
                     app.exitQgis()"
      imports:
        - qgis
        - osgeo.gdal
        - enpt
        - numba

  # ---------------
  # Alias (default)
  # ---------------
  - name: enmapbox
    noarch: generic
    requirements:
      run:
        - enmapbox-full

  # --------------------------
  # Lite version with QGIS LTR
  # --------------------------
  - name: enmapbox-lite-ltr
    noarch: generic
    requirements:
      run:
        - enmapbox-lite
        - qgis ={{ qgis_ltr_version }}

  # --------------------------
  # Full version with QGIS LTR
  # --------------------------
  - name: enmapbox-full-ltr
    noarch: generic
    requirements:
      run:
        - enmapbox-full
        - qgis ={{ qgis_ltr_version }}


about:
  home: https://github.com/EnMAP-Box/enmap-box
  license: GPL-3.0-only
  summary: >
    Meta-package providing all conda dependencies required to run
    several versions of the EnMAP-Box QGIS plugin.
  description: |
    This is a conda meta-package that installs the full runtime
    dependency stack defined in the EnMAP-Box conda environment
    files (e.g. enmapbox_full_latest.yml).

    The EnMAP-Box plugin itself is NOT included and must be installed
    via the QGIS Plugin Manager.

extra:
  recipe-maintainers:
    - jakimowb
    - danschef
