{% set name = "enmapbox-deps" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python>=3.10
    - astropy
    - catboost
    - enpt>=1.2.1
    - enpt_enmapboxapp>=1.0.2
    - enfrosp_enmapboxapp
    - h5py
    - lightgbm
    - lightning
    - matplotlib
    - netcdf4
    - numba>=0.56.4
    - opencv
    - pandas=2.2.3
    - pyopengl
    - pytorch
    - qgis>=3.42.2
    - scikit-learn>=1
    - segmentation-models-pytorch
    - sympy
    - tensorboard
    - torchvision
    - xgboost

test:
  commands:
    # QGIS Python must start
    - |
      export QT_QPA_PLATFORM=offscreen
      python -c "from qgis.core import QgsApplication; \
                 app = QgsApplication([], False); \
                 app.initQgis(); \
                 print('QGIS OK'); \
                 app.exitQgis()"

  imports:
    - qgis
    - osgeo.gdal
    - enpt
    - numba

about:
  home: https://github.com/EnMAP-Box/enmap-box
  license: GPL-3.0-only
  summary: >
    Meta-package providing all conda dependencies required to run
    the EnMAP-Box QGIS plugin.
  description: |
    This is a conda meta-package that installs the full runtime
    dependency stack defined in the EnMAP-Box conda environment
    files (e.g. enmapbox_full_latest.yml).

    The EnMAP-Box plugin itself is NOT included and must be installed
    via the QGIS Plugin Manager.

extra:
  recipe-maintainers:
    - jakimowb
    - danschef
